apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rajesh1816/eks-argocd.git
    targetRevision: main
    path: catalogue
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: roboshop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
