apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: roboshop-backend
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: cart
      - name: catalogue
      - name: payment
      - name: shipping
      - name: user

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/rajesh1816/eks-argocd.git
        targetRevision: main
        path: backend-apps/{{name}}
        helm:
          valueFiles:
            - values-dev.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: roboshop

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true



# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: catalogue-dev
#   namespace: argocd
# spec:
#   project: default

#   source:
#     repoURL: https://github.com/rajesh1816/eks-argocd.git
#     targetRevision: main
#     path: catalogue
#     helm:
#       valueFiles:
#         - values-dev.yaml

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: roboshop

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
